#!/usr/bin/env python
"""Discovery helper for the F51 T-04 fixture.

Takes a list of (sentence, focus) pairs and emits Nakdan options for
the focus word in each. Output is YAML-ready; the human curator adds
gold fields (must_contain / must_not_contain / category).
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from tirvi.adapters.nakdan.client import diacritize_via_api

CASES = [
    # 6 bench cases
    ("האם הקריאה ספר לילדה",                  "האם"),
    ("האם כדאי להקריא ספר",                   "האם"),
    ("האים כדאי להקריא ספר",                  "האים"),
    ("הוא טיפוס שלו ורגוע",                   "שלו"),
    ("זה הספר שלו",                            "שלו"),
    ("כל אם רוצה את הטוב ביותר לילדה",       "לילדה"),

    # mappiq positives
    ("כל אם דואגת לבתה",                       "לבתה"),
    ("כל אישה אוהבת את ילדה",                  "ילדה"),
    ("כל אם נותנת אהבה לילדה",                "לילדה"),
    ("כל אם משחקת עם ילדתה",                  "ילדתה"),
    ("כל בת מקשיבה לאמה",                       "לאמה"),
    ("כל אדם זוכר את אמו",                    "אמו"),
    ("כל אם רוצה את ספרה",                    "ספרה"),

    # mappiq negatives (no possessor trigger)
    ("המשחק הזה מתאים לכל ילד או ילדה",       "ילדה"),
    ("הילדה הולכת לבית הספר",                 "הילדה"),
    ("אני אוהב את הילדה החדשה",                "הילדה"),
    ("ראיתי ילדה ברחוב",                       "ילדה"),

    # she conjoined adjective (calm vs his)
    ("הוא היה שלו ורגוע במהלך כל הבחינה",     "שלו"),
    ("הילד שלו ורגוע אחרי שאכל",               "שלו"),
    ("הספר שלו על השולחן",                     "שלו"),
    ("המכונית שלה חדשה",                       "שלה"),

    # mother / whether
    ("האם אתה יודע את התשובה",                "האם"),
    ("האם החליטה לקנות מתנה",                  "האם"),

    # additional homograph variety
    ("הילד אכל את התפוח",                       "אכל"),
    ("המורה הסביר את החומר",                   "המורה"),
    ("הספר נמצא על המדף",                       "הספר"),
    ("הוא קרא את העיתון",                       "קרא"),
    ("הם הולכים לחנות",                          "הולכים"),
    ("היא רוקדת בשמחה",                          "רוקדת"),
    ("הכלב נובח על הזר",                         "נובח"),
    ("היונה עפה לעץ",                            "עפה"),
]


def main() -> None:
    print("# Auto-generated by scripts/discover_homograph_cases.py")
    print("# Human curator: add must_contain / must_not_contain / category fields.")
    print("schema_version: 1")
    print("cases:")
    for i, (sentence, focus) in enumerate(CASES, 1):
        raw = diacritize_via_api(sentence)
        opts: list[str] = []
        for entry in raw:
            if entry.get("word") == focus:
                opts = list(entry.get("options") or [])
                break
        print(f"  - id: C{i:02d}")
        print(f"    sentence: {sentence!r}")
        print(f"    focus: {focus!r}")
        print(f"    focus_options:")
        for o in opts:
            print(f"      - {o!r}")
    print()


if __name__ == "__main__":
    main()
